site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'

plugins:
  - techdocs-core

nav:
  - Glossary: docs/systemA/glossary.md
  - FAQ: docs/systemA/FAQ.md
